name: Rista Live to GSheet Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug files (VERY IMPORTANT)
      run: |
        echo "Current path:"
        pwd
        echo "Files:"
        ls -R

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        pip install pandas requests PyJWT gspread google-auth

    - name: Run Script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        echo "Running script..."
        python rista_live.py
