name: Rista MTD Update

on:
  schedule:
    # 07:30 AM IST
    - cron: '45 1 * * *'

  workflow_dispatch:

jobs:
  run-mtd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MTD Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

          # IMPORTANT
          RUN_MODE: MTD

        run: |
          echo "Running MTD Update..."
          python rista_mtd_report.py
