name: Run Python Script Every Hour

on:
  schedule:
    # Morning to night (08:00 AM → 11:30 PM IST)
    - cron: '30 2-18 * * *'

    # Midnight to early morning (12:30 AM → 05:30 AM IST)
    - cron: '30 19-23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        echo "Running script..."
        python ./script.py
